# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb_mongoid}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jordan Bracco"]
  s.date = %q{2010-01-14}
  s.description = %q{A plugin for the Merb framework that provides support for MongoID Models.}
  s.email = %q{code@webs.ly}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Generators",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/generators/model.rb",
     "lib/generators/resource_controller.rb",
     "lib/generators/templates/model/app/models/%file_name%.rb",
     "lib/generators/templates/resource_controller/app/controllers/%file_name%.rb",
     "lib/generators/templates/resource_controller/app/views/%file_name%/edit.html.erb",
     "lib/generators/templates/resource_controller/app/views/%file_name%/index.html.erb",
     "lib/generators/templates/resource_controller/app/views/%file_name%/new.html.erb",
     "lib/generators/templates/resource_controller/app/views/%file_name%/show.html.erb",
     "lib/merb/orms/mongoid/connection.rb",
     "lib/merb/orms/mongoid/database.yml.sample",
     "lib/merb_mongoid.rb",
     "merb_mongoid.gemspec",
     "test/helper.rb",
     "test/test_merb_mongoid.rb"
  ]
  s.homepage = %q{http://github.com/webs/merb_mongoid}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A plugin for the Merb framework that provides support for MongoID Models.}
  s.test_files = [
    "test/helper.rb",
     "test/test_merb_mongoid.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<merb-core>, [">= 1.0.9"])
      s.add_runtime_dependency(%q<mongoid>, [">= 1.0.5"])
    else
      s.add_dependency(%q<merb-core>, [">= 1.0.9"])
      s.add_dependency(%q<mongoid>, [">= 1.0.5"])
    end
  else
    s.add_dependency(%q<merb-core>, [">= 1.0.9"])
    s.add_dependency(%q<mongoid>, [">= 1.0.5"])
  end
end

